export const IMAGES = {
  bell: require('../assets/bell.png'),
  user: require('../assets/user.png'),
  back: require('../assets/back.png'),
  remove: require('../assets/remove.png'),
  home: require('../assets/home.png'),
  search: require('../assets/search.png'),
  drawer: require('../assets/drawer.png'),
  heart: require('../assets/heart.png'),
  favourite: require('../assets/favourite.png'),
  star: require('../assets/star.png'),
  settings: require('../assets/setting.png'),
  call: require('../assets/call.png'),
  whats: require('../assets/whatsapp.png'),
  movie: require('../assets/recorder.png'),
};
